---
- hosts: localhost 
  gather_facts: false
  become: true
  vars:
    csvfile: "{{ lookup('file', 'users.csv') }}"
  vars_files:
    - "./vars/main.yml"
  tasks:
    - name: Parse vars from CSV To YAML
      template:
        src: "./vars/main.j2"
        dest: "./vars/main.yml"
      run_once: true
...